导入torch包

In [12]:
import torch
import os, sys
import numpy as nn

试一下分割

得出结论：**你需要先运行导包内容，后面段落的代码再运行时就不需要再导包了**



In [13]:
# import torch
x = torch.empty(5, 3)
print(x)
print(sys.path)
nn.abs(-1)

# 实验结束，开启学习

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])
['/Users/yingmuzhi/Desktop/artificial_intelligence/Learning/DL/section2', '/Users/yingmuzhi/anaconda3/envs/env_cp39_PA/lib/python39.zip', '/Users/yingmuzhi/anaconda3/envs/env_cp39_PA/lib/python3.9', '/Users/yingmuzhi/anaconda3/envs/env_cp39_PA/lib/python3.9/lib-dynload', '', '/Users/yingmuzhi/anaconda3/envs/env_cp39_PA/lib/python3.9/site-packages']


1

本节将介绍如何对内存中的数据进行操作。Pytorch的Tensor和NumPy的多维数组类似，而Tensor提供GPU计算和自动求梯度功能，Tensor更适合深度学习。

### 2.2.1 创建Tensor

In [75]:
'''
2.2.1 创建Tensor
'''
# 用torch.arrage()创建1维Tensor
z = torch.arange(1, 3)
print(z)
print(z.shape)
z = torch.randn(2, 2)
print(z.shape)  # tensor.shape和tensor.size()返回一个tensor([])，其中有几个数反应有几个维度，第一个数代表第一维度有几个元素，第二个数表示第二维度有几个数，以此类推

# 创建5x3未初始化的Tensor
x = torch.empty(5, 3)   # 返回5x3有未初始化数据的张量
print(x)

# 创建5x3随机初始化Tensor
x = torch.rand(5, 3)    # 返回5x3随机初始化数据的张量
print(x)

# 创建5x3的long型全0的Tensor
x = torch.zeros(5, 3, dtype=torch.long) # zero全0，dtype指定数据类型
print(x)

# 直接根据数据创建
x = torch.tensor([5.5, 3])  # 直接创建tensor([])
print(x)

# 根据现有Tensor来创建
x = x.new_ones(5, 3, dtype=torch.float64)   # 创建新tensor，返回相同dtype, device
print(x)
x = torch.randn_like(x, dtype=torch.float)  # 创建新tensor，指定新的dtype
print(x)

# 获取Tensor的形状
print(x.size())
print(x.shape)

# 官网上有很多种创建Tensor的方式，都可以在创建Tensor的时候指定数据类型dtype和存放device(cpu/gpu)

tensor([1, 2])
torch.Size([2])
torch.Size([2, 2])
tensor([[ 0.0000e+00,  3.6893e+19, -2.8455e+24],
        [-2.5250e-29,  1.1210e-44, -0.0000e+00],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00],
        [ 1.4013e-45,  0.0000e+00,  0.0000e+00],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00]])
tensor([[0.1123, 0.4316, 0.1209],
        [0.9542, 0.1427, 0.2661],
        [0.9075, 0.9757, 0.6445],
        [0.8989, 0.8833, 0.2303],
        [0.4268, 0.5302, 0.8775]])
tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])
tensor([5.5000, 3.0000])
tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)
tensor([[ 0.6276,  0.5053,  1.6258],
        [-0.2542, -1.5095,  0.0746],
        [-0.6185,  0.7814, -0.1947],
        [ 0.0511,  1.6160,  0.6769],
        [-0.3482, -0.4944,  0.4832]])
torch.Size([5, 3])
torch.Size([5, 3])


### 2.2.2 操作

#### 加法

In [36]:
'''
2.2.2 操作
加法
'''

# 加法1
y = torch.rand(5, 3)
print(x + y)
# 加法2
print(torch.add(x, y))
# 加法2 - 指定输出模式
result = torch.empty(5, 3)
torch.add(x, y, out=result)
print(result)
# 加法3 - inplace
y.add_(x)
print(y)

tensor([[-1.3064, -0.8150,  1.8010],
        [-0.5182,  0.4842,  1.5001],
        [ 1.4538, -0.8576,  1.2629],
        [ 1.3750,  1.5134, -0.0258],
        [-1.3871, -0.9962, -0.2059]])
tensor([[-1.3064, -0.8150,  1.8010],
        [-0.5182,  0.4842,  1.5001],
        [ 1.4538, -0.8576,  1.2629],
        [ 1.3750,  1.5134, -0.0258],
        [-1.3871, -0.9962, -0.2059]])
tensor([[-1.3064, -0.8150,  1.8010],
        [-0.5182,  0.4842,  1.5001],
        [ 1.4538, -0.8576,  1.2629],
        [ 1.3750,  1.5134, -0.0258],
        [-1.3871, -0.9962, -0.2059]])
tensor([[-1.3064, -0.8150,  1.8010],
        [-0.5182,  0.4842,  1.5001],
        [ 1.4538, -0.8576,  1.2629],
        [ 1.3750,  1.5134, -0.0258],
        [-1.3871, -0.9962, -0.2059]])


#### 索引

torch.Tensor索引功能类似NumPy的索引功能，可以用索引操作来访问Tensor的一部分，需要注意的是：索引出来的结果与原数据共享内存，也即修改一个，另一个会跟着修改。

In [71]:
'''
索引
'''

# 使用Tensor加中括号的方式进行缩影，即Tensor[]，第一个数指示第一个维度，第二个数指示第二个维度，以此类推...
# 使用类似NumPy的索引操作来访问Tensor的一部分，需要注意的是：**若修改索引出来的部分数据，则原数据也会被修改，即共享内存**
x = torch.randn(5, 3)   # 两个维度，第一个维度大小为5，第二个维度大小为3
print("x is a 5x3 Tensor, and its format is: {}".format(x))
y = x[0, :]             # 第一个维度指定为0，其余维度全访问
print("y is a 1x3 Tensor, and its format is: {}".format(y))
y += 1  # 数加，即给矩阵中每个元素加1
print("y' is {}\nx'[0, :] is {}\nThey all changed".format(y, x[0, :]))    # 源x也改变了

x is a 5x3 Tensor, and its format is: tensor([[ 1.1871,  1.7313, -0.0070],
        [ 1.7568, -0.3271,  0.7576],
        [ 0.9035, -1.3489, -0.1099],
        [ 0.6087, -0.7997, -0.2086],
        [-0.8527, -0.3053,  1.2808]])
y is a 1x3 Tensor, and its format is: tensor([ 1.1871,  1.7313, -0.0070])
y' is tensor([2.1871, 2.7313, 0.9930])
x'[0, :] is tensor([2.1871, 2.7313, 0.9930])
They all changed


#### 改变形状

用`view()`来改变`Tensor`形状。

In [72]:
'''
改变形状
'''

print(x)
print(x.shape)
y = x.view(15)
z = x.view(-1, 5)   # -1所指维度可以根据其他维度推算出来
print("x's shape is {}, y's size() is {}, and z's shape is {}".format(x.shape, y.shape, z.shape))

# view只不过将Tensor展平
# view()返回的新Tensor与源Tensor共享内存，改变其中一个，另一个也会改变
print("\ny is {}".format(y))
x += 1
print("x' is {}".format(x))
print("y is {}".format(y))

# reshape()不推荐使用，虽然该函数可以改变形状，但是此函数并不能保证返回的是数据的拷贝

# 为了完全拷贝数据，而不是使用索引（同一块内存），我们推荐用clone()创造副本后再用view()
x_cp = x.clone().view(15)   # 使用clone还有一个好处是会被记录在计算图中，即梯度回传到副本时也会传到源Tensor
print("\nx_cp is {}".format(x_cp))
x -= 1
print("we have made some changes to x_cp, and x_cp now is {}".format(x_cp))

# item()函数也常用，它可以将**不论多少维度，只要是单个一行一列的标量元素Tensor**转换成一个Python number
x = torch.randn(1, 1, 1, 1, 1)  # 5维(5个中括号, 含最外层中括号一共5个)一个元素
print("\n{}".format(x))
print(x.item())
# y = torch.randn(2, 2) # 只能对标量(0维)使用item()
# print(y.item())

# Pytorch 中的 Tensor 支持超过一百种操作

tensor([[ 2.1871,  2.7313,  0.9930],
        [ 1.7568, -0.3271,  0.7576],
        [ 0.9035, -1.3489, -0.1099],
        [ 0.6087, -0.7997, -0.2086],
        [-0.8527, -0.3053,  1.2808]])
torch.Size([5, 3])
x's shape is torch.Size([5, 3]), y's size() is torch.Size([15]), and z's shape is torch.Size([3, 5])

y is tensor([ 2.1871,  2.7313,  0.9930,  1.7568, -0.3271,  0.7576,  0.9035, -1.3489,
        -0.1099,  0.6087, -0.7997, -0.2086, -0.8527, -0.3053,  1.2808])
x' is tensor([[ 3.1871,  3.7313,  1.9930],
        [ 2.7568,  0.6729,  1.7576],
        [ 1.9035, -0.3489,  0.8901],
        [ 1.6087,  0.2003,  0.7914],
        [ 0.1473,  0.6947,  2.2808]])
y is tensor([ 3.1871,  3.7313,  1.9930,  2.7568,  0.6729,  1.7576,  1.9035, -0.3489,
         0.8901,  1.6087,  0.2003,  0.7914,  0.1473,  0.6947,  2.2808])

x_cp is tensor([ 3.1871,  3.7313,  1.9930,  2.7568,  0.6729,  1.7576,  1.9035, -0.3489,
         0.8901,  1.6087,  0.2003,  0.7914,  0.1473,  0.6947,  2.2808])
we have made some changes 

### 2.2.3 广播机制

In [57]:
# arange()和randn()使用
# tensor([])的类型一定如左侧，其中一定是([])元组tuple内一个列表list
x = torch.arange(1, 3)  # 1, 2  start number, end number
y = torch.randn(1, 3) # 1 x 3
print("x is {}, size is {}\nand y is {}, shape is {}".format(x, x.shape, y, y.shape))
z = torch.randn(3, 3)
print(z)

# 广播机制 --- 复制后再相加
x = torch.arange(1, 3).view(1, 2)
print(x)
y = torch.arange(1, 4).view(3, 1)
print(y)
print(x + y)

x is tensor([1, 2]), size is torch.Size([2])
and y is tensor([[-0.2044, -0.1446,  0.9551]]), shape is torch.Size([1, 3])
tensor([[ 0.9148,  0.2893, -0.3741],
        [-1.3647,  0.9492,  0.6205],
        [-0.7172, -0.2807, -1.6604]])
tensor([[1, 2]])
tensor([[1],
        [2],
        [3]])
tensor([[2, 3],
        [3, 4],
        [4, 5]])


### 2.2.4 运算的内存开销

In [63]:
# 索引操作时不会开辟新内存的，而诸如y = x + y这样的加法运算会开辟新内存，将y指向新内存
# 使用python内置id()函数判断内存地址。id()返回十进制内存地址
# hex()将十进制转换为十六进制，hex(id())返回实际十六进制内存地址
x = torch.tensor([1, 2])
y = torch.tensor([3, 4])
id_before = id(y)
y = x + y   # 加法赋值给普通变量会开辟新的内存空间
print("original y is {}, and new y is {}".format(hex(id_before), hex(id(y))))

# 测试python变量内存地址，使用w = x[:] 则给w开辟新的内存空间
z = x
w = x[:]    # python规则，将索引赋值给普通变量会开辟新的内存空间，否则只是传指针
print("\nx's address is {}, z=x z's address is {}, w=x[:] w's address is {}\n".format(hex(id(x)), hex(id(z)), hex(id(w))))

# 使用索引做左值使得内存不变
x_before = hex(id(x))
x[:] = x + y    # 维度和元素个数相同shape，加法赋值给索引变量则不会开辟新空间
print("x origin is {}, and new x is {}".format(x_before, hex(id(x))))

original y is 0x7fde84954b80, and new y is 0x7fde844b2450

x's address is 0x7fde849541d0, z=x z's address is 0x7fde849541d0, w=x[:] w's address is 0x7fde84ba9540

x origin is 0x7fde849541d0, and new x is 0x7fde849541d0


### 2.2.5 Tensor 和 NumPy

我们可以使用`numpy()`和`from_numpy()`将Tensor和NumPy中的数组相互转换。但是需要注意的是：该函数产生的**Tensor和NumPy中的数组共享内存，所以转换得快**。

torch.tensor()会将NumPy数据拷贝为tensor，不再共享内存。

#### Tensor 转 NumPy

In [78]:
'''
Tensor 转 NumPy

使用`numpy()`将`Tensor`转换为NumPy数组
'''

c = torch.ones(5)       # 一维 只有第一维度有5个元素    tensor([]) - 有几个维度，最左边就有几个中括号，最少为1维
a = torch.ones(1, 5)    # 二维 1x5
b = a.numpy()
print(a, b, sep="\t\t")

a += 1
print(a, b, sep="\t\t")

tensor([[1., 1., 1., 1., 1.]])		[[1. 1. 1. 1. 1.]]
tensor([[2., 2., 2., 2., 2.]])		[[2. 2. 2. 2. 2.]]


#### NumPy 转 Tensor

In [80]:
'''from_numpy()'''

import numpy as np

a = np.ones(5)
b = torch.from_numpy(a)
print(a, b, sep="\t\t")

c = torch.tensor(a)
print(c)

[1. 1. 1. 1. 1.]		tensor([1., 1., 1., 1., 1.], dtype=torch.float64)
tensor([1., 1., 1., 1., 1.], dtype=torch.float64)


### 2.2.6 Tensor on GPU

用方法`to()`可以实现CPU和GPU间移动。

In [82]:
# 以下代码只有在PyTorch GPU版本上才会执行
if torch.cuda.is_available():
    device = torch.device("cuda")          # GPU
    y = torch.ones_like(x, device=device)  # 直接创建一个在GPU上的Tensor
    x = x.to(device)                       # 等价于 .to("cuda")
    z = x + y
    print(z)
    print(z.to("cpu", torch.double))       # to()还可以同时更改数据类型
else:
    print("sorry, there is no nvidia-GPU")

sorry, there is no nvidia-GPU
