导入torch包

In [12]:
import torch
import os, sys
import numpy as nn

试一下分割

得出结论：**你需要先运行导包内容，后面段落的代码再运行时就不需要再导包了**

In [13]:
# import torch
x = torch.empty(5, 3)
print(x)
print(sys.path)
nn.abs(-1)

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])
['/Users/yingmuzhi/Desktop/artificial_intelligence/Learning/DL/section2', '/Users/yingmuzhi/anaconda3/envs/env_cp39_PA/lib/python39.zip', '/Users/yingmuzhi/anaconda3/envs/env_cp39_PA/lib/python3.9', '/Users/yingmuzhi/anaconda3/envs/env_cp39_PA/lib/python3.9/lib-dynload', '', '/Users/yingmuzhi/anaconda3/envs/env_cp39_PA/lib/python3.9/site-packages']


1

### 2.2.1 创建Tensor

In [35]:
'''
2.2.1 创建Tensor
'''
# 创建5x3未初始化的Tensor
x = torch.empty(5, 3)
print(x)

# 创建5x3随机初始化Tensor
x = torch.rand(5, 3)
print(x)

# 创建5x3的long型全0的Tensor
x = torch.zeros(5, 3, dtype=torch.long)
print(x)

# 直接根据数据创建
x = torch.tensor([5.5, 3])
print(x)

# 根据现有Tensor来创建
x = x.new_ones(5, 3, dtype=torch.float64)
print(x)
x = torch.randn_like(x, dtype=torch.float)  # 指定新的数据类型
print(x)

# 获取Tensor的形状
print(x.size())
print(x.shape)

# 官网上有很多种创建Tensor的方式，都可以在创建Tensor的时候指定数据类型dtype和存放device(cpu/gpu)

tensor([[0.0000e+00, 1.4013e-45, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00],
        [1.1704e-41, 0.0000e+00, 2.2369e+08],
        [0.0000e+00, 0.0000e+00, 0.0000e+00]])
tensor([[0.1236, 0.8112, 0.1711],
        [0.1610, 0.7297, 0.3009],
        [0.1941, 0.9683, 0.3542],
        [0.7760, 0.9145, 0.8681],
        [0.4423, 0.5590, 0.3052]])
tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])
tensor([5.5000, 3.0000])
tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)
tensor([[-1.5763, -1.2797,  1.6908],
        [-0.8850,  0.2311,  0.9754],
        [ 0.9174, -1.4748,  0.5364],
        [ 0.5297,  1.0145, -0.8939],
        [-1.4179, -1.2042, -0.8497]])
torch.Size([5, 3])
torch.Size([5, 3])


### 2.2.2 操作

In [36]:
'''
2.2.2 操作
加法
'''

# 加法1
y = torch.rand(5, 3)
print(x + y)
# 加法2
print(torch.add(x, y))
# 加法2 - 指定输出模式
result = torch.empty(5, 3)
torch.add(x, y, out=result)
print(result)
# 加法3 - inplace
y.add_(x)
print(y)

tensor([[-1.3064, -0.8150,  1.8010],
        [-0.5182,  0.4842,  1.5001],
        [ 1.4538, -0.8576,  1.2629],
        [ 1.3750,  1.5134, -0.0258],
        [-1.3871, -0.9962, -0.2059]])
tensor([[-1.3064, -0.8150,  1.8010],
        [-0.5182,  0.4842,  1.5001],
        [ 1.4538, -0.8576,  1.2629],
        [ 1.3750,  1.5134, -0.0258],
        [-1.3871, -0.9962, -0.2059]])
tensor([[-1.3064, -0.8150,  1.8010],
        [-0.5182,  0.4842,  1.5001],
        [ 1.4538, -0.8576,  1.2629],
        [ 1.3750,  1.5134, -0.0258],
        [-1.3871, -0.9962, -0.2059]])
tensor([[-1.3064, -0.8150,  1.8010],
        [-0.5182,  0.4842,  1.5001],
        [ 1.4538, -0.8576,  1.2629],
        [ 1.3750,  1.5134, -0.0258],
        [-1.3871, -0.9962, -0.2059]])


In [37]:
'''
索引
'''

# 使用类似NumPy的索引操作来访问Tensor的一部分，需要注意的是：**若修改索引出来的部分数据，则原数据也会被修改，即共享内存**
print("x is {}".format(x))
y = x[0, :]
print("y is {}".format(y))
y += 1  # 数加，即给矩阵中每个元素加1
print("y' is {}\nx'[0, :] is {}".format(y, x[0, :]))    # 源x也改变了

x is tensor([[-1.5763, -1.2797,  1.6908],
        [-0.8850,  0.2311,  0.9754],
        [ 0.9174, -1.4748,  0.5364],
        [ 0.5297,  1.0145, -0.8939],
        [-1.4179, -1.2042, -0.8497]])
y is tensor([-1.5763, -1.2797,  1.6908])
y' is tensor([-0.5763, -0.2797,  2.6908])
x'[0, :] is tensor([-0.5763, -0.2797,  2.6908])


In [38]:
'''
改变形状
'''
print(x)
print(x.shape)
y = x.view(15)
z = x.view(-1, 5)   # -1所指维度可以根据其他维度推算出来
print("x's shape is {}, y's size() is {}, and z's shape is {}".format(x.shape, y.shape, z.shape))

# view()返回的新Tensor与源Tensor共享内存，改变其中一个，另一个也会改变
print("\ny is {}".format(y))
x += 1
print("x' is {}".format(x))
print("y is {}".format(y))

# reshape()不推荐使用，虽然该函数可以改变形状，但是此函数并不能保证返回的是数据的拷贝

# 为了完全拷贝数据，而不是使用索引（同一块内存），我们推荐用clone()创造副本后再用view()
x_cp = x.clone().view(15)   # 使用clone还有一个好处是会被记录在计算图中，即梯度回传到副本时也会传到源Tensor
print("\nx_cp is {}".format(x_cp))
x -= 1
print("we have made some changes to x_cp, and x_cp now is {}".format(x_cp))

# item()函数也常用，它可以将**标量Tensor**转换成一个Python number
x = torch.randn(1)
print("\n{}".format(x))
print(x.item())
# y = torch.randn(2, 2) # 只能对标量(0维)使用item()
# print(y.item())

# Pytorch 中的 Tensor 支持超过一百种操作

tensor([[-0.5763, -0.2797,  2.6908],
        [-0.8850,  0.2311,  0.9754],
        [ 0.9174, -1.4748,  0.5364],
        [ 0.5297,  1.0145, -0.8939],
        [-1.4179, -1.2042, -0.8497]])
torch.Size([5, 3])
x's shape is torch.Size([5, 3]), y's size() is torch.Size([15]), and z's shape is torch.Size([3, 5])

y is tensor([-0.5763, -0.2797,  2.6908, -0.8850,  0.2311,  0.9754,  0.9174, -1.4748,
         0.5364,  0.5297,  1.0145, -0.8939, -1.4179, -1.2042, -0.8497])
x' is tensor([[ 0.4237,  0.7203,  3.6908],
        [ 0.1150,  1.2311,  1.9754],
        [ 1.9174, -0.4748,  1.5364],
        [ 1.5297,  2.0145,  0.1061],
        [-0.4179, -0.2042,  0.1503]])
y is tensor([ 0.4237,  0.7203,  3.6908,  0.1150,  1.2311,  1.9754,  1.9174, -0.4748,
         1.5364,  1.5297,  2.0145,  0.1061, -0.4179, -0.2042,  0.1503])

x_cp is tensor([ 0.4237,  0.7203,  3.6908,  0.1150,  1.2311,  1.9754,  1.9174, -0.4748,
         1.5364,  1.5297,  2.0145,  0.1061, -0.4179, -0.2042,  0.1503])
we have made some changes 

### 2.2.3 广播机制

In [57]:
# arange()和randn()使用
# tensor([])的类型一定如左侧，其中一定是([])元组tuple内一个列表list
x = torch.arange(1, 3)  # 1, 2  start number, end number
y = torch.randn(1, 3) # 1 x 3
print("x is {}, size is {}\nand y is {}, shape is {}".format(x, x.shape, y, y.shape))
z = torch.randn(3, 3)
print(z)

# 广播机制 --- 复制后再相加
x = torch.arange(1, 3).view(1, 2)
print(x)
y = torch.arange(1, 4).view(3, 1)
print(y)
print(x + y)

x is tensor([1, 2]), size is torch.Size([2])
and y is tensor([[-0.2044, -0.1446,  0.9551]]), shape is torch.Size([1, 3])
tensor([[ 0.9148,  0.2893, -0.3741],
        [-1.3647,  0.9492,  0.6205],
        [-0.7172, -0.2807, -1.6604]])
tensor([[1, 2]])
tensor([[1],
        [2],
        [3]])
tensor([[2, 3],
        [3, 4],
        [4, 5]])


### 2.2.4 运算的内存开销

In [63]:
# 索引操作时不会开辟新内存的，而诸如y = x + y这样的加法运算会开辟新内存，将y指向新内存
# 使用python内置id()函数判断内存地址。id()返回十进制内存地址
# hex()将十进制转换为十六进制，hex(id())返回实际十六进制内存地址
x = torch.tensor([1, 2])
y = torch.tensor([3, 4])
id_before = id(y)
y = x + y
print("original y is {}, and new y is {}".format(hex(id_before), hex(id(y))))

# 测试变量内存地址，使用w = x[:] 则给w开辟新的内存空间
z = x
w = x[:]
print("\nx's address is {}, z=x z's address is {}, w=x[:] w's address is {}\n".format(hex(id(x)), hex(id(z)), hex(id(w))))

# 使用索引做左值使得内存不变
x_before = hex(id(x))
x[:] = x + y
print("x origin is {}, and new x is {}".format(x_before, hex(id(x))))

original y is 0x7fde84954b80, and new y is 0x7fde844b2450

x's address is 0x7fde849541d0, z=x z's address is 0x7fde849541d0, w=x[:] w's address is 0x7fde84ba9540

x origin is 0x7fde849541d0, and new x is 0x7fde849541d0
